all:
	#g++ -Wall -ansi -pedantic -O3 -funroll-loops -march=core2 impulse.cpp
	#g++ -Wall -ansi -pedantic -O3 -march=core2 impulse.cpp
	g++ -Wall -ansi -pedantic -O3 -o impulse impulse.cpp

debug:
	g++ -Wall -ansi -pedantic -g -pg -DDEBUG -o impulse impulse.cpp

profile:
	g++ -Wall -ansi -pedantic -O3 -funroll-loops -g -pg -o impulse impulse.cpp

